import React from 'react';
import { 
  Bars3Icon,
  DocumentIcon,
  ArrowDownTrayIcon,
  FolderIcon,
  CalendarIcon
} from '@heroicons/react/24/outline';
import { useChat } from '../../context/ChatContext';
import { format, isToday, isYesterday, startOfDay } from 'date-fns';

interface FilesSidebarProps {
  isOpen: boolean;
  onToggle: () => void;
}

export const FilesSidebar: React.FC<FilesSidebarProps> = ({ isOpen, onToggle }) => {
  const { files } = useChat();

  // Group files by date
  const groupedFiles = files.reduce((groups, file) => {
    const dateKey = format(startOfDay(file.createdAt), 'yyyy-MM-dd');
    if (!groups[dateKey]) {
      groups[dateKey] = [];
    }
    groups[dateKey].push(file);
    return groups;
  }, {} as Record<string, typeof files>);

  const getDateLabel = (dateStr: string) => {
    const date = new Date(dateStr);
    if (isToday(date)) return 'Today';
    if (isYesterday(date)) return 'Yesterday';
    return format(date, 'MMM d, yyyy');
  };

  const formatFileSize = (bytes: number) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  const getFileIcon = (type: string) => {
    if (type.includes('image')) return '🖼️';
    if (type.includes('pdf')) return '📄';
    if (type.includes('document') || type.includes('word')) return '📝';
    if (type.includes('spreadsheet') || type.includes('excel')) return '📊';
    if (type.includes('presentation') || type.includes('powerpoint')) return '📋';
    return '📁';
  };

  return (
    <>
      {/* Mobile backdrop */}
      {isOpen && (
        <div 
          className="fixed inset-0 bg-black bg-opacity-50 z-20 lg:hidden"
          onClick={onToggle}
        />
      )}
      
      {/* Sidebar */}
      <div className={`
        fixed inset-y-0 right-0 z-30 w-80 bg-white border-l border-gray-200 transform transition-transform duration-300 ease-in-out
        lg:relative lg:translate-x-0
        ${isOpen ? 'translate-x-0' : 'translate-x-full'}
      `}>
        <div className="flex flex-col h-full">
          {/* Header */}
          <div className="flex items-center justify-between p-4 border-b border-gray-200">
            <div className="flex items-center space-x-2">
              <FolderIcon className="h-5 w-5 text-gray-500" />
              <h2 className="text-lg font-semibold text-gray-900">Generated Files</h2>
            </div>
            <button
              onClick={onToggle}
              className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors lg:hidden"
            >
              <Bars3Icon className="h-5 w-5" />
            </button>
          </div>

          {/* Files List */}
          <div className="flex-1 overflow-y-auto">
            {Object.keys(groupedFiles).length === 0 ? (
              <div className="flex flex-col items-center justify-center h-full text-center p-6">
                <DocumentIcon className="h-12 w-12 text-gray-300 mb-4" />
                <h3 className="text-lg font-medium text-gray-500 mb-2">No files yet</h3>
                <p className="text-sm text-gray-400">
                  Files generated by the AI will appear here
                </p>
              </div>
            ) : (
              <div className="p-4 space-y-6">
                {Object.entries(groupedFiles)
                  .sort(([a], [b]) => new Date(b).getTime() - new Date(a).getTime())
                  .map(([dateKey, dateFiles]) => (
                    <div key={dateKey}>
                      <div className="flex items-center space-x-2 mb-3">
                        <CalendarIcon className="h-4 w-4 text-gray-400" />
                        <h3 className="text-sm font-medium text-gray-500">
                          {getDateLabel(dateKey)}
                        </h3>
                      </div>
                      <div className="space-y-2">
                        {dateFiles
                          .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
                          .map((file) => (
                            <div
                              key={file.id}
                              className="group flex items-center justify-between p-3 bg-gray-50 hover:bg-gray-100 rounded-lg transition-colors cursor-pointer"
                            >
                              <div className="flex items-center space-x-3 flex-1 min-w-0">
                                <span className="text-lg">
                                  {getFileIcon(file.type)}
                                </span>
                                <div className="flex-1 min-w-0">
                                  <p className="text-sm font-medium text-gray-900 truncate">
                                    {file.name}
                                  </p>
                                  <div className="flex items-center space-x-2 text-xs text-gray-500">
                                    <span>{formatFileSize(file.size)}</span>
                                    <span>•</span>
                                    <span>{format(file.createdAt, 'HH:mm')}</span>
                                  </div>
                                </div>
                              </div>
                              <button
                                onClick={() => {
                                  // Download file
                                  const link = document.createElement('a');
                                  link.href = file.url;
                                  link.download = file.name;
                                  link.click();
                                }}
                                className="opacity-0 group-hover:opacity-100 p-1 text-gray-400 hover:text-blue-600 transition-opacity"
                                title="Download file"
                              >
                                <ArrowDownTrayIcon className="h-4 w-4" />
                              </button>
                            </div>
                          ))}
                      </div>
                    </div>
                  ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
};
